Started logging messages at Wed Jun 25 13:37:57 2014
Info:    Using UV tolerance 1e-006
Info:    Using UV tolerance 1e-006
Info:    HwNlibToTSLib options selected:
Info:        Points: Off
Info:        Curves: On
Info:        Surfaces: Off
Info:        BReps: On
Info:        Do not create IwAssembly/IwAssemblyInstance objects
Info:        Making untrimmed surfaces into BReps
Info:        Making solids into single BReps
Info:        Make components of failed trims
Info:        Make faces of failed B-reps
Info:    HW SAT v1.2.6-maint
Info:    Reading 
Info:    Processing 
Info:    Transferring 
Info:    
Info:    Found 0 points in file
Info:    Found 0 curves in file
Info:    Found 0 surfaces in file
Info:    Found 0 trimmed surfaces in file
Info:    Found 7 B-reps in file
Info:    Found 4 B-rep faces in file
Info:    
Info:    Using 3D tolerance 1e-006
Info:    Working on 0
Info:        Working on 94
Info:            Created 
Info:        Working on 98
Info:            Created 
Info:        Working on 34
Info:            Created 
Info:        Working on 101
Info:            Created 
Info:        Working on 102
Info:            Created 
Info:        Working on 43
Info:            Created 
Info:        Working on 54
Info:            Created 
Info:        Working on 73
Info:            Created 
Info:        Created 
Info:    Working on BRep 0
Info:        Using 3D tolerance 1.1122e-006
Info:        Using 3D tolerance 1e-006
Info:        Created BRep 
Info:    Working on 1
Info:        Working on 81
Info:            Created 
Info:        Created 
Info:    Working on curve 1
Info:        Created curve 
Info:    Working on 2
Info:        Working on 82
Info:            Created 
Info:        Working on 83
Info:            Created 
Info:        Created 
Info:    Working on curve 2
Info:        Created curve 
Info:    Working on 3
Info:        Working on 84
Info:            Created 
Info:        Created 
Info:    Working on curve 3
Info:        Created curve 
Info:    Working on 4
Info:        Working on 85
Info:            Created 
Info:        Created 
Info:    Working on curve 4
Info:        Created curve 
Info:    Working on 5
Info:        Working on 86
Info:            Created 
Info:        Created 
Info:    Working on curve 5
Info:        Created curve 
Info:    Working on 6
Info:        Working on 87
Info:            Created 
Info:        Created 
Info:    Working on curve 6
Info:        Created curve 
Info:    Finished with 
Info:    Points:                 0 found       0 created       0 failed
Info:    Coordinate Systems      0 found       0 created       0 failed
Info:    Curves:                 6 found       6 created       0 failed
Info:    Surfaces:               0 found       0 created       0 failed
Info:    Trimmed Surfaces:       0 found       0 created       0 failed
Info:    Breps:                  1 found       1 created       0 failed
Finished logging messages at Wed Jun 25 13:37:57 2014
